### ISSUE TITLE
Не инициирована переменная $fields

### ISSUE THREAD

**Issue by Rugento** [retailcrm/magento-module#30]
Не инициирована переменная $fields, поэтому весь код ниже никогда не отработает.
Откуда ее нужно брать?

https://github.com/retailcrm/magento-module/blob/c2c2fa0a95a402ca52bca56b64dab1d1c428eaed/src/Model/History/Exchange.php#L630

**Comment by gwinn** [comment]
Спасибо за замечание. В данный момент по модулю ведется комплекс доработок, учтем и этот момент.
