### ISSUE TITLE
Где указать путь к директории для сохранения  ICML файла?

### ISSUE THREAD

**Issue by Woleref** [retailcrm/magento-module#7]
Сейчас сохраняет файл в корне пользователя.
Ubuntu 16.04 + NGINX 1.12 + PHP 7.0 + Magento 2.1.8 +Redis + Varnish

**Comment by gwinn** [comment]
Файл сохраняется в корне сайта, это не конфигурируемая опция.

**Comment by Woleref** [comment]
Проблема в том, что сохраняется файл в корне пользователя, а не в корне сайта.

**Comment by gwinn** [comment]
Возможно проблема с настройками окружения

**Comment by Woleref** [comment]
Поправил
